#!/bin/bash
echo "/tmp/iamafile: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2,BuildID[sha1]=a6cb40078351eHfuExHWosQAiWGCyVBHiyjavBWRTe4,forGNU/Linux 3.2.0, stripped"
